version: '3.8'

services:
  caddy-zurg:
    build:
      context: /etc/zurg/caddy-plugin-zurg/
      dockerfile: Dockerfile.caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/zurg/caddy-plugin-zurg/Caddyfile:/etc/caddy/Caddyfile:ro
      - /etc/zurg/caddy-plugin-zurg/error_videos:/etc/zurg/caddy-plugin-zurg/error_videos:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - HOSTNAME=${HOSTNAME:-zurg.example.com}
      - ZURG_BACKEND=${ZURG_BACKEND:-host.docker.internal:9999}
    restart: unless-stopped
    networks:
      - caddy

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy:
    driver: bridge